spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/imobiliaria
        username: postgres
        password: 123456
        tomcat:
            testOnBorrow: true
            validationQuery:  SELECT 1
        sqlScriptEncoding:  UTF-8
    jpa:
        hibernate:
            ddlAuto: update
        showSql: true
    